fsprojects/FSharpPlus

FSharpPlus/Samples/Learn You a Haskell.fsx
Added FSharpPlus.Operators. This .fsx crashes without this module..
=> Update Learn You a Haskell.fsx

docsrc/content/abstraction-monad.fsx
Not sure if I had to put it as `Bind` or as `(>>=)`, let's see what you say :)
=> Fixing (hopefully!) Bind signature

docsrc/content/abstraction-applicative.fsx
https://github.com/wallymathieu/fsharp-validations/pull/4#issuecomment-354602173
=> The operator is flipped <| should be |>

FSharpPlus.sln, src/FSharpPlus.Samples/FSharpPlus.Samples.fsproj, src/FSharpPlus.Samples/Program.fs, src/FSharpPlus.Samples/paket.references, src/FSharpPlus/Samples/Applicatives.fsx, src/FSharpPlus/Samples/Collections.fsx, src/FSharpPlus/Samples/Comonads.fsx, src/FSharpPlus/Samples/Conversions.fsx, src/FSharpPlus/Samples/Fold.fsx, src/FSharpPlus/Samples/GenericMath.fsx, src/FSharpPlus/Samples/Haskell.fsx, src/FSharpPlus/Samples/Iso.fsx, src/FSharpPlus/Samples/Learn You a Haskell.fsx, src/FSharpPlus/Samples/Lens.fsx, src/FSharpPlus/Samples/MonadTransformers.fsx, src/FSharpPlus/Samples/Monads.fsx, src/FSharpPlus/Samples/ParallelArrays.fsx, src/FSharpPlus/Samples/Prism.fsx, src/FSharpPlus/Samples/Split-Join.fsx, src/FSharpPlus/Samples/Traversal.fsx, src/FSharpPlus/Samples/ZipLists.fsx, src/FSharpPlus/SamplesFromFsControl/Collections.fsx, src/FSharpPlus/SamplesFromFsControl/Converter.fsx, src/FSharpPlus/SamplesFromFsControl/Functions.fsx, src/FSharpPlus/SamplesFromFsControl/Haskell.fsx, src/FSharpPlus/SamplesFromFsControl/Numerics.fsx
- This is to compile the samples, should fix part of https://github.com/gusty/FSharpPlus/issues/56
- This should be cleaner than https://github.com/gusty/FSharpPlus/pull/62#issuecomment-354683044 since it's using standard build infrastructure to compile
=> Samples project

docsrc/content/abstraction-bifunctor.fsx, docsrc/content/abstraction-contravariant.fsx, src/FSharpPlus/Operators.fs
I've added a bit more documentation based on some reading of docs by Edward Kmett. Does it look OK?
=> Adding more documentation for contravariant, bifunctor et.c.

src/FSharpPlus/Samples/Cont.fsx
- Ported [examples](https://gist.github.com/wallymathieu/ad8fe3d5b85875cf6f487ad0180be660) to F#+
=> Example usage of F#+ Cont

src/FSharpPlus/FSharpPlus.fsproj
=> Don't include "App.config" in .NET Core build.

src/FSharpPlus/Error.fs, tests/FSharpPlus.Tests/General.fs
- ChoiceT as same type of implementation as ResultT
This is intended to fix #99
=> Adding ChoiceT

build.fsx, src/FSharpPlus/FSharpPlus.fsproj
- Question: what should the copyright text say?
=> Adding copyright and correct iconurl

src/FSharpPlus/Functor.fs, src/FSharpPlus/Internals.fs, src/FSharpPlus/Monoid.fs
This proposal is not arbitrary at all, but it's a bit restrictive in the sense that it require at least a semigroup on the error type.
=> + Alt and Semigroup for Result and Choice

.gitignore, src/FSharpPlus/Collection.fs, src/FSharpPlus/Indexable.fs, tests/FSharpPlus.Tests/General.fs
Adding some tests in order to demonstrate that readonly collection works with f#+
=> Indexable, Foldable and readonly collections

src/FSharpPlus/Samples/MonadTrans.fsx
This fixes #19 
Uses sample code compiled from [FSharpPlus.Suave](https://github.com/wallymathieu/FSharpPlus.Suave), [Suave](https://github.com/SuaveIO/suave) and #19
=> Sample usage of OptionT and ResultT

docsrc/content/abstractions.fsx, docsrc/content/abstractions.plantuml
Tested on:
* Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Firefox 52.0 (64-bit)
* Opera 56.0.3051.40
* Internet Explorer 11.345.17134.0
* Microsoft Edge 42.17134.1.0
Fixes #75.
=> Add styles on abstraction diagram and adjust plantuml settings.

README.md
- Add Markdown badge (intended to add a commit)
=> + Appveyor badge

docsrc/content/computation-expressions.fsx, src/FSharpPlus/Builders.fs
Have I understood it correctly?
=> Suggestion about docs

src/FSharpPlus/Samples/MonadTrans.fsx
Copy of answer from https://stackoverflow.com/questions/37852147/combination-monads-in-f/37900264#37900264 and updated to use ResultT instead of ErrorT
I've looked trough the examples https://github.com/fsprojects/FSharpPlus/issues/135#issuecomment-435334718 and added one of them
=> Copy of monad transform sample from stackoverflow

docsrc/content/lens.fsx, src/FSharpPlus/Lens.fs, tests/FSharpPlus.Tests/Lens.fs
=> Manipulate Map using lenses

src/FSharpPlus/Extensions.fs, tests/FSharpPlus.Tests/Extensions.fs
as discussed yesterday with @gusty# and since I was there, created a few more unit tests to improve coverage.
=> fixed union return type on IReadOnlyDictionary 

src/FSharpPlus/Operators.fs, src/FSharpPlus/Tuple.fs, tests/FSharpPlus.Tests/General.fs
=> Add polyvariadic curry / uncurry functions

src/FSharpPlus/Samples/Learn You a Haskell.fsx
Changes:
- Initial whitespace cleanup
- Additional comments denoting result values
- Type annotation for `readMaybe` (L:494)
=> Update 'Learn You a Haskell' sample

src/FSharpPlus/Memoization.fs, tests/FSharpPlus.Tests/General.fs
Motivated by the discussion in #155
=> Rename memoize to memoizeN

appveyor.yml, build.fsx
This PR adds a nupkg to the appveyor artifacts, fixing #170.
=> Add nupkg generation to CI

src/FSharpPlus/Extensions.fs
=> Match String.findIndex signature/implementation to the convention

src/FSharpPlus/Operators.fs
=> Add bind function

src/FSharpPlus/Extensions.fs
Also added some documentation while at it
=> Rename IReadOnlyList.add to trySetItem

DEVELOPER_GUIDE.md, README.md
Few notes inbetween knowledge I've gained through @gusty help on F#+ idioms and the meager things I know about type classes.
Obviously needs more work, but hope it helps by defining few holes to fill in describing said idioms.
=> bootstrapping developer guide

docsrc/content/applicative-functors.fsx
Attempt to address https://github.com/fsprojects/FSharpPlus/issues/204
=> Explain list and function functor similarities

FSharpPlus.sln, RELEASE_NOTES.md, docsrc/content/abstraction-bifoldable.fsx, docsrc/tools/templates/abstractions.plantuml, src/FSharpPlus/Bifoldable.fs, src/FSharpPlus/FSharpPlus.fsproj, src/FSharpPlus/Monoids.fs, src/FSharpPlus/Operators.fs, src/FSharpPlus/Validations.fs, tests/FSharpPlus.Tests/BifoldableTests.fs, tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
This is going to be a long and non-optimal journey towards #213.
Opening here to leverage the CI and getting input from people aware of idioms of implementation in this library.
=> Bifoldable abstraction

docsrc/tools/templates/abstractions.plantuml
Sorry, I forgot to adjust the diagram in the Bifoldable PR
=> fix bifold and add bisum in plantuml diagram

src/FSharpPlus/Extensions.fs
Adds a function to create a safe version of potentially unsafe functions.
=> Add protect function

src/FSharpPlus/Extensions.fs
This attempts to address some functions requested in #229
=> + Some Choice and Result functions

src/FSharpPlus/Error.fs, src/FSharpPlus/List.fs, src/FSharpPlus/Operators.fs, src/FSharpPlus/Option.fs, src/FSharpPlus/Seq.fs, src/FSharpPlus/State.fs, tests/FSharpPlus.Tests/General.fs
=> Add more functions to State

src/FSharpPlus/Validations.fs
- Align to standard XML comments
- Fully annotate types
- Add `protect`, `toChoice`, `ofChoice`  functions
=> Improve Validation

src/FSharpPlus/Monoid.fs, src/FSharpPlus/Monoids.fs, src/FSharpPlus/Numeric.fs
=> Use XOR as default monoid for bool

src/FSharpPlus/FSharpPlus.fsproj
This makes it possible to set additional OtherFlags in Directory.Build.props
=> adjust other flags

README.md
Adding link to #FSharpPlus on FP Slack
=> Added link to FP slack

src/FSharpPlus/Operators.fs
Regression in https://github.com/fsprojects/FSharpPlus/commit/804cf417a34328e7dc7fb2b37bf00479d54353ab
=> Fixes un/curry to allow arguments of different types

.github/workflows/dotnetcore.yml
This will add another build.
This one will be with Github's actions.
=> Add Windows build with github actions

.travis.yml, appveyor.yml
This means that for for some pull requests we get double builds
=> Build on all fsproject branches

src/FSharpPlus/FSharpPlus.fsproj
=> Fix Fable compilation

.github/workflows/dotnetcore.yml
Also on pull requests to master
=> Configure github action to run on pull requests to master

docsrc/content/abstraction-monad.fsx
This example is based on @gusty answer to my question in https://github.com/fsprojects/FSharpPlus/issues/301.
It builds on the previous example in the doc showing how you can add one more layer.
=> Adds an example for stacked monad transformers

src/FSharpPlus/Data/DList.fs, tests/FSharpPlusFable.Tests/FSharpTests/Extensions.fs
Address #307 
Add tests to pin and document behavior.
=> + Fix DList equality for Fable

src/FSharpPlus/Control/Indexable.fs, tests/FSharpPlus.Tests/General.fs, tests/FSharpPlus.Tests/Helpers.fs
This will allow mapi implementation on external types
=> Add clean signature to all Indexables

src/FSharpPlus/Control/Alternative.fs, src/FSharpPlus/Control/Applicative.fs, src/FSharpPlus/Control/Foldable.fs, src/FSharpPlus/Control/Functor.fs, src/FSharpPlus/Control/Monad.fs, src/FSharpPlus/Control/Monoid.fs, src/FSharpPlus/Control/Traversable.fs, src/FSharpPlus/Data/NonEmptyList.fs, src/FSharpPlus/Data/NonEmptyMap.fs, src/FSharpPlus/Data/NonEmptySeq.fs, src/FSharpPlus/Data/NonEmptySet.fs, src/FSharpPlus/FSharpPlus.fsproj, tests/FSharpPlus.Tests/ComputationExpressions.fs, tests/FSharpPlus.Tests/General.fs
=> Add NonEmptySeq

src/FSharpPlus/Extensions/Array.fs, src/FSharpPlus/Extensions/Async.fs, src/FSharpPlus/Extensions/Choice.fs, src/FSharpPlus/Extensions/Dict.fs, src/FSharpPlus/Extensions/Dictionary.fs, src/FSharpPlus/Extensions/Enumerator.fs, src/FSharpPlus/Extensions/IList.fs, src/FSharpPlus/Extensions/IReadOnlyDictionary.fs, src/FSharpPlus/Extensions/Lazy.fs, src/FSharpPlus/Extensions/List.fs, src/FSharpPlus/Extensions/Map.fs, src/FSharpPlus/Extensions/ResizeArray.fs, src/FSharpPlus/Extensions/Result.fs, src/FSharpPlus/Extensions/Seq.fs, src/FSharpPlus/Extensions/String.fs, src/FSharpPlus/Extensions/Task.fs
Have a bit more time to get back into FSharpPlus so started in on some more API docs...
Now documents over Extensions pretty completely. Tried to follow conventions.
Please review the "Enumerator" file as it was a little tricky, choosing what to omit, etc.
=> More docs - starting to go through the extensions

src/FSharpPlus/Data/Cont.fs, tests/FSharpPlus.Tests/ComputationExpressions.fs
This adds the `Cont.eval` function and also its respective version for `ContT`.
=> + Cont.eval / ContT.eval

src/FSharpPlus/Control/Collection.fs, src/FSharpPlus/Extensions/Dict.fs, src/FSharpPlus/Extensions/Dictionary.fs, src/FSharpPlus/Extensions/IReadOnlyDictionary.fs, src/FSharpPlus/Extensions/Map.fs, tests/FSharpPlus.Tests/General.fs
Added in Extensions and in generic `choose`
=> Introduce choose function to Map, Dictionary, IDictionary and IReadOnlyDictionary

src/FSharpPlus/Control/Foldable.fs, src/FSharpPlus/Operators.fs, tests/FSharpPlus.Tests/General.fs
=> Add tryLast to Foldable

src/FSharpPlus/Data/NonEmptyList.fs, src/FSharpPlus/Extensions/Array.fs, src/FSharpPlus/Extensions/List.fs, src/FSharpPlus/Extensions/ResizeArray.fs, tests/FSharpPlus.Tests/Data.fs, tests/FSharpPlus.Tests/Extensions.fs
It's a similar idea to already introduced `zipShortest`.
=> Introduce map2Shortest function

src/FSharpPlus/Control/Functor.fs, tests/FSharpPlus.Tests/General.fs
When working on Functor.Map2, I've found some duplications/redundancies in Functor.Map.
Changed it and added missing tests for Async.
=> DRY in Functor.Map

src/FSharpPlus/Control/Traversable.fs
First off, let me say that this library is AMAZING. My mind is completely blown. Nice. Seriously.
Now, on to the matter at hand:
The generic implementation of sequence uses arrays, specifically `Array.append`, which is linear in the length of the array. This means the entire operation is of exponential order. Sequencing a 1_000_000 element array on my i9 9900K takes longer than I have the patience to wait (more than a minute).
With that said, this pull request changes the implementation to use the usual list cons operation, which happens in constant time, with a linear List.rev at the end, which brings the order of the entire operation down to linear. A 10_000_000 item array (10 times as many elements) is now sequenced in under 4 seconds (about 3.7 seconds, to be more precise). I didn't …
=> Use list instead of array for the generic implementation of sequence

docsrc/content/lens.fsx
I think Lens example is clearer when using update expression. 
Rewriting all record values by hand seems like suboptimal practice, that doesn't scale for more record fields.
Also, I've added examples of updating a value through lens.
=> Simplify Lens docs

src/FSharpPlus/Control/Indexable.fs, src/FSharpPlus/Extensions/Array.fs, src/FSharpPlus/Extensions/Dict.fs, src/FSharpPlus/Extensions/Dictionary.fs, src/FSharpPlus/Extensions/List.fs, src/FSharpPlus/Extensions/Map.fs, src/FSharpPlus/Extensions/Option.fs, src/FSharpPlus/Extensions/Seq.fs, src/FSharpPlus/Operators.fs, tests/FSharpPlus.Tests/Extensions.fs, tests/FSharpPlus.Tests/General.fs
Added generic `choosei` for types:
* List
* Array
* Seq
* Map
* Dictionary
* Dict
=> Added generic choosei

docsrc/content/type-reader.fsx
=> +Example from F# Online

src/FSharpPlus/Data/Free.fs, tests/FSharpPlus.Tests/Free.fs
=> Fix signature of Free.fold.

src/FSharpPlus/Control/Comonad.fs, src/FSharpPlus/Control/Monad.fs, src/FSharpPlus/Control/Monoid.fs, src/FSharpPlus/Extensions/Task.fs, tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj, tests/FSharpPlus.Tests/Helpers.fs, tests/FSharpPlus.Tests/Task.fs
Our current implementation is very naïve, for instance it doesn't propagate exceptions properly.
Here we attempt to handle:
- Exceptions
- Cancellations
- Short-circuits
=> Update Task extensions so they can handle exceptions and cancellations

src/FSharpPlus/Extensions/Option.fs, tests/FSharpPlus.Tests/Extensions.fs
Add function for conversion of C# try pattern to F# option.
=> + Option.ofPair

README.md
Since the compilation takes too much time on travis, travis thinks that the build has stalled.
=> - Travis build status

docsrc/content/computation-expressions.fsx
This will hopefully add some light about how to use properly lazy/strict CEs
=> Add additional information about CEs

src/FSharpPlus/Data/Validation.fs
This will add the `SequenceBiApply` function as an overloaded method for Validation, which was requested many times.
Also the `partition` function, which already exists in `Result`.
This closes #272
=> + SequenceBiApply and partition to Validation

docsrc/content/index.fsx
update the script sample to use nuget reference
=> nuget: FSharpPlus

.config/dotnet-tools.json, src/FSharpPlus/Control/Applicative.fs, src/FSharpPlus/Control/Functor.fs, src/FSharpPlus/Control/Monad.fs, src/FSharpPlus/Control/Numeric.fs, src/FSharpPlus/Data/Monoids.fs, src/FSharpPlus/Extensions/Enumerator.fs, src/FSharpPlus/Lens.fs, tests/FSharpPlusFable.Tests/FSharpPlusFable.Tests.fsproj, tests/FSharpPlusFable.Tests/FSharpTests/Extensions.fs, tests/FSharpPlusFable.Tests/FSharpTests/General.fs, tests/FSharpPlusFable.Tests/FSharpTests/General/Indexable.fs, tests/FSharpPlusFable.Tests/FSharpTests/General/Lensing.fs, tests/FSharpPlusFable.Tests/FSharpTests/General/Monad.fs, tests/FSharpPlusFable.Tests/FSharpTests/General/Numeric.fs, tests/FSharpPlusFable.Tests/package.json
Include more of F#+ to Fable since more of it is working in later versions of Fable.
=> Bump to Fable 3.1.15

src/FSharpPlus/Parsing.fs
This is an attempt to use a different method to hide internal stuff.
If it works well we can possibly apply it to other modules.
=> Better hiding of internals in parsing

src/FSharpPlus/Extensions/Seq.fs, tests/FSharpPlus.Tests/Extensions.fs
=> Fix Seq.drop.

src/FSharpPlus/Extensions/Array.fs, src/FSharpPlus/Extensions/Enumerator.fs, src/FSharpPlus/Extensions/List.fs
=> Address some F#6 warnings

.github/workflows/dotnetcore.yml, appveyor.yml
Configure Feed as in https://dusted.codes/github-actions-for-dotnet-core-nuget-packages
The project feed from AppVeyor:
https://ci.appveyor.com/nuget/fsharpplus
=> + Nuget feed

DEVELOPER_GUIDE.md
An attempt to clarify the ideas expressed there.
=> Reword 1st part of the dev guide

src/FSharpPlus/Data/Validation.fs, src/FSharpPlus/Extensions/Extensions.fs, src/FSharpPlus/Extensions/List.fs, src/FSharpPlus/Extensions/Result.fs
=> Use ListCollector

README.md
New, shiny links (who work) =D
=> Update FP Slack link

src/FSharpPlus/Control/Functor.fs, src/FSharpPlus/Extensions/Option.fs, src/FSharpPlus/Extensions/Result.fs
This will add unzip, zip, zip3 for Result and make it a ZipFunctor.
It will also add `zip3` for Option.
=> Some missing Option, Result zip functions

.config/dotnet-tools.json, docsrc/tools/docsTool.fsproj
=> Bump F# formatting

docsrc/content/type-seqt.fsx, src/FSharpPlus/Data/Seq.fs, src/FSharpPlus/Extensions/AsyncEnumerable.fs, src/FSharpPlus/Extensions/Observable.fs, src/FSharpPlus/FSharpPlus.fsproj, tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj, tests/FSharpPlus.Tests/SeqT.fs
This PR will attempt to reintroduce the new SeqT with more expectations regarding collections.
We might not be able to cover all cases but at least try to get a good compromise.
=> Bring back SeqT

.github/workflows/dotnetcore.yml, src/FSharpPlus/Extensions/ResizeArray.fs, src/FSharpPlus/Extensions/String.fs
This should resolve (at least part) of https://github.com/fsprojects/FSharpPlus/issues/395
=> Fix null handling for ResizeArray.fs and Strings.fs

.github/CODEOWNERS
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
The intent of this pull request is to add default reviewers for pull requests.
=> +CODEOWNERS

docsrc/content/extension-methods.fsx, src/FSharpPlus.Docs/Samples/Conversions.fsx, src/FSharpPlus/Data/NonEmptyList.fs, src/FSharpPlus/Data/Validation.fs, src/FSharpPlus/Extensions/Choice.fs, src/FSharpPlus/Extensions/Extensions.fs, src/FSharpPlus/Extensions/IReadOnlyDictionary.fs, src/FSharpPlus/Extensions/List.fs, src/FSharpPlus/Extensions/Result.fs, src/FSharpPlus/Operators.fs, tests/FSharpPlus.Tests/Validations.fs
This is part of the cleanup involved in moving forward into v2.
=> Remove Obsoletes for v2

docsrc/content/applicative-functors.fsx, docsrc/content/type-free.fsx, docsrc/content/type-seqt.fsx, src/FSharpPlus.Docs/Samples/Learn You a Haskell.fsx, src/FSharpPlus.TypeLevel/FSharpPlus.TypeLevel.fsproj, src/FSharpPlus.TypeLevel/Providers/FSharpPlus.Providers.fsproj, src/FSharpPlus/Control/Monad.fs, src/FSharpPlus/Data/NonEmptyList.fs, tests/CSharpLib/CustomerId.cs, tests/FSharpPlusFable.Tests/FSharpPlusFable.Tests.fsproj, tests/FSharpPlusFable.Tests/FSharpTests/General/Monoid.fs, tests/FSharpPlusFable.Tests/FSharpTests/General/MonoidCompile.fs, tests/benchmarks/ExtensionsBenchmarks.fs
Build is becoming quite noisy, hard to spot the interesting parts when something goes wrong.
There is an accumulation on intentional and unintentional warnings to address/suppress.
=> Cleanup warning noise

src/FSharpPlus/Builders.fs, src/FSharpPlus/Control/Alternative.fs, src/FSharpPlus/Control/Applicative.fs, src/FSharpPlus/Control/Foldable.fs, src/FSharpPlus/Control/Functor.fs, src/FSharpPlus/Control/Monad.fs, src/FSharpPlus/Control/Monoid.fs, src/FSharpPlus/Control/Traversable.fs, src/FSharpPlus/Control/ZipApplicative.fs, src/FSharpPlus/Data/NonEmptySeq.fs, src/FSharpPlus/FSharpPlus.fsproj, src/FSharpPlus/Internals.fs, tests/FSharpPlus.Tests/Traversals.fs
This is a (rebased) continuation from #552
=> NonEmptySeq with static members (cont)

src/FSharpPlus/Parsing.fs, tests/FSharpPlus.Tests/Parsing.fs
=> (|Scanned|_|)
