- build.fsx
- docsrc/tools/generate.fsx
- src/FSharpPlus.BaseLib/FSharpPlus.BaseLib.csproj
- src/FSharpPlus/FSharpPlus.fsproj
Note also build status on appveyor:
[![Build status](https://ci.appveyor.com/api/projects/status/4b2d96u78cousu1v/branch/pack_for_net45_on_nix?svg=true)](https://ci.appveyor.com/project/wallymathieu/fsharpplus-8q142/branch/pack_for_net45_on_nix)
Need to verify that the package is generated as it should.
> Using msbuild to package FSharpPlus

- build.fsx
Mainly to be able to get more reproducible builds locally
- Clean up folders before compiling anything
- Set version and version prefix in variables so that it gets set to correct versions when building
- Build using msbuild instead of dotnet (this helps when building on other OS's than Windows)
> MsBuild should be aware of version prefix and suffix

- docsrc/content/abstraction-functor.fsx
as I understand `fmap` is part of Haskell compatibility
> Shouldn't it use the default name for map?

- src/FSharpPlus/Cont.fs
- src/FSharpPlus/Error.fs
- src/FSharpPlus/Foldable.fs
- src/FSharpPlus/Identity.fs
- src/FSharpPlus/Kleisli.fs
- src/FSharpPlus/Lens.fs
- src/FSharpPlus/List.fs
- src/FSharpPlus/Monoids.fs
- src/FSharpPlus/Option.fs
- src/FSharpPlus/Reader.fs
- src/FSharpPlus/Seq.fs
- src/FSharpPlus/State.fs
- src/FSharpPlus/Writer.fs
Operations like ``bind`` make heavy use of wrapping-unwrapping. In order to avoid additional pressure on the GC we can set all wrapper types to structs.
> Wrapper types as structs

- tests/FSharpPlus.Tests/General.fs
Trouble is that parsing DateTime depends on machine configuration and how the tests are executed.
When using F#+ and executing the tests in [a repository](https://github.com/wallymathieu/DateTimeBehaviorOnTravisAndAppveyor) based on the MiniScaffold template we notice that the behavior is consistent. While executing using NUnit2 test runner on mono Mac OS X, mono on Linux image on Travis and .net on Windows image on Appveyor gives different behaviors.
In order to not to fix something in F#+ for which there is a library that [solves DateTime issues](https://github.com/nodatime/nodatime/), better to ignore the discrepancies.
> Moving parse DateTime to separate test

- src/FSharpPlus/Cont.fs
- src/FSharpPlus/DList.fs
- src/FSharpPlus/Error.fs
- src/FSharpPlus/Monoids.fs
- src/FSharpPlus/NonEmptyList.fs
- src/FSharpPlus/Option.fs
- src/FSharpPlus/ParallelArray.fs
- src/FSharpPlus/Reader.fs
- src/FSharpPlus/Seq.fs
- src/FSharpPlus/State.fs
- src/FSharpPlus/Writer.fs
- src/FSharpPlus/ZipList.fs
I've applied `[<EditorBrowsable(EditorBrowsableState.Never)>]` to the below types in case where you might use the explicit type name in order to operate on data.
- `DList`, `ZipList`, `ParallelArray`, `NonEmptyList`
- `ResultT`
- `ContT`
- `OptionT`
- `Reader`, `ReaderT`
- `SeqT`
- `State`, `StateT`
- `Writer`, `WriterT`
See https://github.com/gusty/FSharpPlus/issues/84#issuecomment-372952783
> In order to avoid confusing intellisense

- src/FSharpPlus/Monoid.fs
- tests/FSharpPlus.Tests/Validations.fs
This could be very convenient for accumulative Validations and possible to alternative validation if we decide to define them as requiring a semigroup on the error parameter.
> Exceptions and AggregateExceptions as Semigroup

- docsrc/content/abstraction-monoid.fsx
- docsrc/content/abstraction-semigroup.fsx
- src/FSharpPlus/Internals.fs
- src/FSharpPlus/Monoid.fs
- src/FSharpPlus/Numeric.fs
- src/FSharpPlus/Operators.fs
- src/FSharpPlus/Tuple.fs
- tests/FSharpPlus.Tests/General.fs
- tests/FSharpPlus.Tests/Lens.fs
This removes tuple size limitation.
It also makes available the overloads for both syntactic and system tuples.
The only limitation is for lenses, because MapItemX functions will start returning system tuples for tuples of size greater than 7, when writing.
This is due a wart in the current design of the F# compiler, which only converts tuples when size is less than 8.
> - Tuple size limitation

- appveyor.yml
- build.fsx
I didn't manage to make the documentation generation run on AppVeyor, but even building and running tests on a Windows box seems beneficial.
@gusty , if you decide to merge that can you take care of turning on the AppVeyor build and adding the badge to the readme?
Link to passing build on my AppVeyor account:
https://ci.appveyor.com/project/gdziadkiewicz/fsharpplus/builds/19799286
> Fix AppVeyor build, add tests results uploading and build version patching.

- src/FSharpPlus/FSharpPlus.fsproj
- src/FSharpPlus/Memoization.fs
- tests/FSharpPlus.Tests/General.fs
Fixes #88 
Note that I tried making the helper type `T` private, but found no way to make it compile. We might consider giving it an awful name that is less likely to collide with anything user-defined.
> Add polyvariadic memoization

- src/FSharpPlus.Samples/FSharpPlus.Samples.fsproj
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
This allows overriding the paths for locating F# compiler, SDK mainly used for the F# compiler to build F#+ with a freshly built "experimental" compiler (with overriding the used msbuild properties here).
> Preparing for compiler test suite

- .travis.yml
Issue with using pack on travis due to paket. Since the main source of packages is Appveyor, there is little need to generate package on Travis.
> Update travis yml and paket restore targets

- src/FSharpPlus/FSharpPlus.fsproj
- src/FSharpPlus/Parsing.fs
- tests/FSharpPlus.Tests/General.fs
This will add the `scanf` family of functions, strong typed and working with tuples of any size.
They return a tuple whose type should be known at compile-time.
These new functions are:
- scanf
- sscanf
- parseArray
And the `try...`version of each of them.
Probably the most interesting one is `sscanf` which will simplify extraction data from strings, and its trySscanf variant.
Internally they use the `parse` function, from this library.
> Polyvariadic parsing functions

- src/FSharpPlus/Collection.fs
- src/FSharpPlus/Extensions.fs
- src/FSharpPlus/Foldable.fs
- src/FSharpPlus/Indexable.fs
- tests/FSharpPlus.Tests/Extensions.fs
Related:  fsharp/fslang-suggestions#102 
Closes #158.
This PR adds more string functions to the String module (in Extensions.fs), and use them as the implementation of existing generic functions.
"Part 1" means we have some functions left to be discussed in detail and they are not going to be added in this PR.
See #158 for the discussion.
TODO:
* Add the following functions ((*) Generic version already exists):
* Replace the implementation of following generic functions with the new ones:
* Add some tests for: (skipped trivial functions)
> Extend string module - Part 1

- src/FSharpPlus/Cont.fs
- src/FSharpPlus/Error.fs
- src/FSharpPlus/List.fs
- src/FSharpPlus/Option.fs
- src/FSharpPlus/Reader.fs
- src/FSharpPlus/Seq.fs
- src/FSharpPlus/State.fs
- src/FSharpPlus/Writer.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
This will fix #156 
The idea is that these members need to be defined in such a way that they can "talk" about these constructions with their inner (or outer, depends on the convention) monad.
As showed by the provided repro: no matter if the transformer is not a delayed monad, its outer monad could be a delayed one and would know how to handle these methods.
> Add missing cexpr members to Monad Transformers

- src/FSharpPlus/Extensions.fs
- src/FSharpPlus/Functor.fs
- tests/FSharpPlus.Tests/General.fs
This PR adds an overload of `<*>` for `Task`, as well as some helpful extensions to the `Task` module.
> Add Task Applicative instance

- src/FSharpPlus/Memoization.fs
Tried to integrate it a bit better at both internal code level and end user.
I would love to have the function in Operators (and the type in Control) but it seems it have to be interleaved in order to delay overload resolution.
> Align memoizeN code with F#+

- src/FSharpPlus/Builders.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
This will fix `use` for strict computation expressions #183
> Fix 'use' for strict builders

- src/FSharpPlus/Extensions.fs
- src/FSharpPlus/Traversable.fs
- tests/FSharpPlus.Tests/General.fs
This will allow to traverse infinite sequences.
Performance will be worst, when performing this operation in parallel, because of the internal `async.RunSynchronously` speaking at low level, or the fact that it becomes really a blocking sequence speaking at high level.
But in cases where performance is required and the sequence is finite, the way to go should be to make it an array.
> Make Async.Sequence (and Traverse) lazy

- src/FSharpPlus/Error.fs
- src/FSharpPlus/Free.fs
- src/FSharpPlus/Internals.fs
- src/FSharpPlus/List.fs
- src/FSharpPlus/Option.fs
- src/FSharpPlus/Seq.fs
- src/FSharpPlus/State.fs
- src/FSharpPlus/Writer.fs
- tests/FSharpPlus.Tests/General.fs
This is a way to workaround #23 
Actually, the root cause of it which is the linked F# compiler bug.
Constraints generated by the IlxGen are affected by the optimizer which is the root cause of many of the unsolved type variables errors.
> Workaround F# type inference bug

- docsrc/content/abstraction-functor.fsx
- src/FSharpPlus/Coproduct.fs
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/Free.fs
A Coproduct of two functors is like a `Choice<'FunctorL<'T>,'FunctorR<'T>>`  which results in a single functor.
This is useful for combining Free monad's functors, as a cheap alternative to using a Free monad transformer.
> + Coproduct

- src/FSharpPlus/Free.fs
Looks like now that we were forced to use the `Free.run` function there's no big reason for `FreeNode` to mediate.
> Unify Free and FreeNode in a single DU

- README.md
- docsrc/content/index.fsx
Please review...
I tried to integrate with what was already there, but put all the links in on the fsproject index page.
I initially wanted the README to be a replica of the fsprojects index, but later felt that they should have different focus - the README should be intro to what it's about, where as the index is more full overview.
I'm keen to see how we can auto generate docs for extensions so that they can be separated nicely with a link to "Extensions". We could always do a manually written index, but would prefer auto.
> Simplify README, and move most body/links to index

- src/FSharpPlus/Extensions.fs
Non generic `catch` functions have the arguments flipped with respect to the generic version.
This could be useful for using forward pipe expressions, but now we have `defaultWith` for that in Result, so this function is redundant. It would be better to have it with the arguments the same way as the generic.
For `Choice` we can add a function, maybe something like `bind2Of2`.
> Deprecate non-generic catch

- src/FSharpPlus/Control/MonadTrans.fs
- src/FSharpPlus/Extensions.fs
This is because defaultWith is not a replacement for catch since catch produces a Result/Choice, where-as defaultWith unwraps.
> Add bindError and bindChoice2Of2, and offer in deprecation notice

- src/FSharpPlus/Extensions/IReadOnlyDictionary.fs
- src/FSharpPlus/Lens.fs
- tests/FSharpPlus.Tests/Lens.fs
The existing Map._item isn't a nice lens to work with since the getter/view returns type Option<'a> but the setter receives 'a.  That is, it violates the lens law of setting what you get doesn't change anything `set l (view l s) s ~ s` (It doesn't even compile.)
I added the _at lens https://hackage.haskell.org/package/lens-4.18.1/docs/Control-Lens-At.html#t:At which both the getter and setter use Option<'a>.
I also added non (https://hackage.haskell.org/package/lens-4.18.1/docs/Control-Lens-Iso.html#v:non) which works well together with _at.
> Lens: add _at and non for working with Maps

- src/FSharpPlus/Data/ParallelArray.fs
- src/FSharpPlus/Data/Reader.fs
- src/FSharpPlus/Data/State.fs
- src/FSharpPlus/Data/ZipList.fs
- src/FSharpPlus/Operators.fs
- src/FSharpPlus/Samples/Learn You a Haskell.fsx
- tests/FSharpPlus.Tests/General.fs
Add liftA function and replace all of the usages of liftA2.
Related: #234
> #234 rename lifta2 to lift2

- docsrc/content/extensions.fsx
- docsrc/content/index.fsx
- docsrc/tools/generate.fsx
- docsrc/tools/templates/template.fsx
- src/FSharpPlus/Extensions/Enumerator.fs
Still WIP, but want to put this up for discussion.
The idea was to more conversationally introduce extensions from perspective of utility to user, rather than list off like an API doc.
I dumped all the functions into the doc, which was useful to 'see' them all, but not sure they'll stay -- can just link to the appropriate API doc. However, might still be useful to group within a module (eg map, apply, bind together) instead of alphabetical ordering default of API.
> Document extensions

- docsrc/content/type-validation.fsx
Moving movie validations on the top of documentation. I think this example is more friendlier than the lens versions.
> Move movie validations at the top

- src/FSharpPlus/Control/Alternative.fs
- src/FSharpPlus/Control/Applicative.fs
- src/FSharpPlus/Control/Traversable.fs
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/General.fs
This PR will offer a general solution for #41 
The solution presented here adds a (redundant) method to `Apply` intended for internal use, called `IsLeftZeroForApply`.
The theory behind it is that a binary operation can have one (or more) left-zero elements, a left zero element is a element `z` such that:
z * e = z
So, we add overloads of this method for some types that we can tell about their left-zero elements. But for types that are Alternatives we don't need an overload because:
empty <*> f = empty
Which means we can use that knowledge automatically.
For types we can't tell about their left-zero elements we don't add an overload.
> Generalize short-circuit for Traverse

- docsrc/content/generic-doc.fsx
- docsrc/content/index.fsx
- docsrc/content/operators-common.fsx
- src/FSharpPlus/Operators.fs
Addressed questions, https://github.com/fsprojects/FSharpPlus/pull/278/commits/ecd430114b6bd88d949684fbd3da12526ae24baf
...and then added these new commits:
Add two missed docs on choose and replace in Operators:
https://github.com/fsprojects/FSharpPlus/pull/278/commits/8111022e0fa3e146287c10979154761f0c5fd021
Add new index for Operators - first section is on "common" ones since they don't fall under any specific abstraction:
https://github.com/fsprojects/FSharpPlus/pull/278/commits/63d7b9f8393f6aae0125fe78e3035d72a0831043
I was thinking to detail the other generic operators in the appropriate abstraction page which often already does in it's 'minimal definition' and 'additional operator' sections. 
eg: http://fsprojects.github.io/FSharpPlus/abstraction-functor.html#map
If ok, I'll merge …
> Adz document generic ops

- src/FSharpPlus/Builders.fs
- src/FSharpPlus/Control/Monad.fs
- src/FSharpPlus/Data/Cont.fs
- src/FSharpPlus/Data/Free.fs
- src/FSharpPlus/Data/Reader.fs
- src/FSharpPlus/Data/State.fs
- src/FSharpPlus/Data/Validations.fs
- src/FSharpPlus/Samples/Learn You a Haskell.fsx
- tests/FSharpPlus.Tests/ComputationExpressions.fs
This PR will switch the default for `delay` to the one that it's technically correct for delayed builders.
Auto-sense had to be adjusted because the bind operation inside this delay implementation would fail with a null value.
Also, type inference is a bit more complicate which forced me to add a specific delay for Free<'T> with a trivial implementation since it's not a "delayed monad".
It would be interesting to add more testing and see if there is a change in functionality, good or bad (breaking).
> Better default for Delay

- docsrc/content/abstraction-misc.fsx
- src/FSharpPlus/Control/Alternative.fs
- src/FSharpPlus/Control/Foldable.fs
- src/FSharpPlus/Data/NonEmptyList.fs
- src/FSharpPlus/FSharpPlus.fsproj
- src/FSharpPlus/Operators.fs
- tests/FSharpPlus.Tests/General.fs
This PR will add an Invoker for the `choice` function.
It will allow to run the function over semigroups of Alt's (Alternatives without zero), which is a common use case.
Most overloads will use the technique of a left-zero knowledge to support short-circuit.
Note that Left Zero here (in contrast to the applicative implementation) is implemented in such a way that it's always defined (defaulting to false). Which simplifies a bit the constraint solving.
This also adds the `Reducible` abstraction which is a Foldable special case where there's no need for a Zero value, or initial state to fold. This means that the `reduce` function is safe.
> +Choice Invoker

- src/FSharpPlus/Lens.fs
- tests/FSharpPlus.Tests/Lens.fs
The `filtered` equivalent for `List.choose`.
Test case includes a nested traversal.
> Implement choosed

- tests/FSharpPlus.Tests/ComputationExpressions.fs
From the issue : https://github.com/Microsoft/visualfsharp/issues/1436
The test associated with the fix:
```f#
[<Test>]
member this.``OnCancel.RaceBetweenCancellationAndDispose``() = 
let flag = ref 0
let cts = new System.Threading.CancellationTokenSource()
let go = async {
use disp =
cts.Cancel()
{ new IDisposable with
override __.Dispose() = incr flag }
while true do
do! Async.Sleep 50
}
try
Async.RunSynchronously (go, cancellationToken = cts.Token)
with
#if FX_NO_OPERATION_CANCELLED
_ -> ()
#else
:? System.OperationCanceledException -> ()
#endif
Assert.AreEqual(1, !flag)
```
In order to get the same test for monad.fx, we port the more minimal test.
> Make async test of cancellation and dispose behavior more deterministic on CI

- src/FSharpPlus/Data/ZipList.fs
ZipList is implemented with sequences which have (unfortunate) referential equality.
Ideally sequences don't implement equality as that present many problems, including enumerating infinite sequences.
We can't fix sequences, but we can fix ZipList.
As an example of what potential problems this would bring, imagine an optimization like the one used for IsLeftZero which defaults to comparing to the empty element, it would fail, but not having comparison would skip that overload.
> No equality for ZipList

- src/FSharpPlus/Control/Collection.fs
- tests/FSharpPlus.Tests/General.fs
This will fix #320 for F# versions 4.7 and lower by removing the Default1 overload which is an optimization.
It is expected that future versions of the F# compiler will fix this issue, so this patch won't be needed anymore.
Therefore in the future event of a release of this library which targets a min compiler version which doesn't have this issue, this patch can be revisited and removed.
> Fix intercalate's generic overload

- src/FSharpPlus/Control/Traversable.fs
- tests/FSharpPlus.Tests/General.fs
This is a fix for a regression detected in v1.1.0
Closes #316
> Fix traverse for seq of asyncs

- docsrc/content/abstraction-functor.fsx
- docsrc/content/abstraction-semigroup.fsx
- docsrc/content/abstraction-traversable.fsx
- docsrc/content/type-nonempty-map.fsx
- docsrc/content/type-nonempty-set.fsx
- src/FSharpPlus/Data/NonEmptyMap.fs
- src/FSharpPlus/Data/NonEmptySet.fs
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/General.fs
Close #342.
Related: #351
This PR implements `NonEmptySet` and `NonEmptyMap`.
TODO:
> Add NonEmptySet and NonEmptyMap

- src/FSharpPlus/Control/Monad.fs
- src/FSharpPlus/Data/Reader.fs
- src/FSharpPlus/Data/State.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
This will generate a compile error when attempting to use a try .. with construction inside a non-strict computation expression over a type that doesn't provide a `TryWith` implementation.
Same applies to `TryFinally`.
For reference: http://tryjoinads.org/docs/computations/monads.html
_For monadic computations that encapsulate untracked F# effects, the members TryWith and TryFinally cannot be implemented in terms of other operations. They need to understand the structure of the computation, in order to wrap the appropriate call that actually runs the effects with try .. with or try .. finally._ 
It also fixes the behavior of lazy monad transformers by adding a special Invoker for them, which takes strict monad defaults into consideration, allowing the composition of lazy with strict …
> Fix try blocks for lazy / strict monads

- src/FSharpPlus/Control/Collection.fs
In collections, some parameter order from the Invoker on instance (external types) is wrong.
> Fix bug: wrong parameters order for externals

- src/FSharpPlus/Data/NonEmptyList.fs
- tests/FSharpPlus.Tests/General.fs
This implementation would save one allocation per element.
> Better nel builder implementation

- src/FSharpPlus/Builders.fs
- src/FSharpPlus/Control/Monad.fs
With this PR we'll attempt to do as much as possible to help non-expert CE users to use generic CEs the right way.
**To recap:**
- when using a generic CE we have to take into account whether the type involved is lazy or not. The default CE: `monad` is lazy. 
- if we use a lazy CE with a strict type, bad things can happen, from runtime errors to infinite loops, but as long as we don't use any advanced construct (try block, using or while) everything should work fine in any case.
So, regarding the advanced constructs:
- for loops have a run-time "auto-sense" feature that checks if the type is really lazy, if is not they call the strict version of the construct.
- try blocks have a compile-time check, since a lazy monad needs to define them, if they are not present a compiler error tells …
> Display warning for while loops inside lazy computation expressions for non-lazy types

- tests/FSharpPlus.Tests/ComputationExpressions.fs
- tests/FSharpPlus.Tests/General.fs
- tests/FSharpPlus.Tests/Helpers.fs
Q: Type was wrong, I wonder how test were passing, or would they break now :)
A: Yes, they break, but I can't read the expected result
So, we're using here areEquivalent to check side-effects and adding a helper to check directly side effects against expectations.
And of course, as last step we can fix our expectations and everything should be green again.
> Fix and enhance CE tests

- src/FSharpPlus/Control/Collection.fs
- src/FSharpPlus/Control/Functor.fs
- src/FSharpPlus/Extensions/IReadOnlyCollection.fs
- tests/FSharpPlus.Tests/General.fs
Recently I've been using F#+ to interop with some C# stuff, and I came across the IReadonlyCollection case.
It was described in RFC: https://github.com/fsprojects/FSharpPlus/issues/109
The conclusion was, that PRs that introduce ReadOnly methods will be accepted.
I've introduced IReadOnlyCollection in OfSeq, OfList, Map and Iter
> Add IReadOnlyCollection to OfSeq, OfList, Map and Iter

- src/FSharpPlus/Data/NonEmptyList.fs
- src/FSharpPlus/Data/NonEmptyMap.fs
- src/FSharpPlus/Data/NonEmptySeq.fs
- src/FSharpPlus/Data/NonEmptySet.fs
- tests/FSharpPlus.Tests/General.fs
This adds a type alias for all non empty collections and also a CE builder `NonEmptySeq` which will have the same identifier as its type alias.
The existing builder for `NonEmptyList` will match its type alias, aligning this way with `seq` (type alias and CE), the old `nel` remains available for backwards compatibility.
Finally this adds two range operators for non-empty sequences: `|..` and `..|`.
This will close #363
> Add type alias for non-empty collections and builder for NonEmptySeq

- src/FSharpPlus/Control/Foldable.fs
- src/FSharpPlus/Extensions/String.fs
- tests/FSharpPlus.Tests/General.fs
Add `tryHead` and `tryLast` to String.
Add tests to generic tryHead and simplify it using FSharp.Core instead of hand-written implementation.
> + String.tryHead and tryLast, test tryHead, simplify

- docsrc/content/lens.fsx
Simplify Prism docs using update expression.
Capitalize record field names according to MS F# style guide.
Format code.
Add remark on polymorphic update and `with` expression incompatibility.
> Simplify and format Prism docs

- src/FSharpPlus/Control/Applicative.fs
- tests/FSharpPlus.Tests/General.fs
… in case the function contains side-effects.
fixes #398
> `apply` for functions evaluates (chronologically) left-to-right

- src/FSharpPlus/Data/NonEmptySeq.fs
`NonEmptySeq.ofSeq` uses `Seq.isEmpty` to check if the sequence is actually non-empty.
But `Seq.isEmpty` evaluates the first element of the sequence to do that, so using `ofSeq` may trigger the side effects.
```fsharp
let s = seq {printfn "a"; 1; printfn "b"; 2; printfn "c"; 3; }
let ns = NonEmptySeq.ofSeq s // prints "a"
```
This can be problematic when a user know the sequence is non-empty and does not want to trigger the said side effects. This PR makes the internal function `unsafeOfSeq` public for that purpose, with some document comments to indicate that user should normally use `ofSeq`.
TODO:
> Make NonEmptySeq.unsafeOfSeq public

- src/FSharpPlus/Extensions/String.fs
`String.drop` is a safe version of `String.skip`, which intends to protect a call to `String.skip` with arguments which would cause an exception, and instead return an empty string.
However, the comparison of the length of the input string with the number of characters to drop is inverted. When it would be safe to drop the requested number of characters from the input string, `String.drop` will instead return an empty string; and when the requested number of characters exceeds the length of the input string, `String.drop` will cause the exception from `String.skip`.
The solution is to invert the comparison.
> Inverted length comparison in String.drop

- src/FSharpPlus/Builders.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
Added `yield!` operator to monad.plus, so that yield behavior is consistent with return behavior and with FSharp.Core collections expressions.
> + `yield!` to monad.plus

- src/FSharpPlus/Data/NonEmptyList.fs
- tests/FSharpPlus.Tests/Data.fs
- tests/FSharpPlus.Tests/Validations.fs
Change FsCheck usage to a version that throws exceptions when properties are not fulfilled.
> Bugfix: NonEmptyList.map2Shortest, Fix FsCheck tests

- src/FSharpPlus/Control/Traversable.fs
- tests/FSharpPlus.Tests/General.fs
This is mostly a reveral of fixes introduced in: https://github.com/fsprojects/FSharpPlus/commit/75d95689d43da448d3bfc67ed6ffe051648cea9c
There is no failing case, so I assume this could work.
Tests are constructed on implicit assumptions (e.g. magic numbers 4 and 5). Maybe we should improve them?
> Fix finite applicatives traversal tests

- src/FSharpPlus/Control/Traversable.fs
- tests/FSharpPlus.Tests/General.fs
This PR add short circuit for traversing non-lazy collections and also fixes mapping next element after short-circuiting lazy collections (solves #415), since right now it stops at the first error but maps over the next element after the error, which shouldn't be necessary.
> Fix short-circuiting Traverse

- src/FSharpPlus/Operators.fs
This active pattern was named wrongly, in the opposite direction.
The correct name should be something that was parsed, not something that would parse.
> Rename Parse active pattern

- docsrc/content/extensions.fsx
- docsrc/content/lens.fsx
- src/FSharpPlus/Extensions/Array.fs
- src/FSharpPlus/Extensions/List.fs
- src/FSharpPlus/Lens.fs
- tests/FSharpPlus.Tests/Extensions.fs
- tests/FSharpPlus.Tests/Lens.fs
Noticed this hadn't been added after the discussion the other day - so here it is.
I've added an Array module for the same behavior - but with slightly differing semantics owing to the nature of Array.
> Add indexer lens for List and Array

- docsrc/content/abstraction-applicative.fsx
- src/FSharpPlus/Builders.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
- tests/FSharpPlus.Tests/General.fs
By adding a type parameter to the builders and using it as much as possible in non-constrained methods we can sort of define specialized builders, like:
let task<'t> = monad'<System.Threading.Tasks.Task<'t>>
Type inference won't be worst, it's yet to be proven a slight improve by finding an actual case, but worst case scenario doing:
let x = task { ... }
will be the same as doing
let x: Task<_> = monad' { ... }
> Allow specialized builders for generic CEs

- src/FSharpPlus/Data/NonEmptyList.fs
- src/FSharpPlus/Data/NonEmptyMap.fs
- src/FSharpPlus/Data/NonEmptySeq.fs
- src/FSharpPlus/Data/NonEmptySet.fs
- src/FSharpPlus/Extensions/Array.fs
- src/FSharpPlus/Extensions/Choice.fs
- src/FSharpPlus/Extensions/Dictionary.fs
- src/FSharpPlus/Extensions/Lazy.fs
- src/FSharpPlus/Extensions/List.fs
- src/FSharpPlus/Extensions/Map.fs
- src/FSharpPlus/Extensions/ResizeArray.fs
- src/FSharpPlus/Extensions/Result.fs
- src/FSharpPlus/Extensions/Seq.fs
- src/FSharpPlus/Operators.fs
See https://github.com/fsprojects/FSharpPlus/runs/1943273443
> Fix wrong parameters in XML comments

- src/FSharpPlus/Control/Traversable.fs
- tests/FSharpPlus.Tests/General.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Traversable.fs
> Evaluate `traverse` left to right

- src/FSharpPlus/Extensions/Result.fs
I am not sure if this is a good design, so did this PR to get started the discussion.
The problem is that, as opposed to `Option.get` where the error doesn't carry any information, in `Result` we normally carry a description of what happened. By using `get` when the value is an `Error` an exception is thrown, hiding the error description.
Of course, we don't know the error type, but in case of an error we can do our best to match on the type and try to throw a better exception.
Comments?
> + Internal error to Result.get

- src/FSharpPlus/Parsing.fs
- tests/FSharpPlus.Tests/General.fs
> Add support for %o %x and %X to scan functions

- src/FSharpPlus/Parsing.fs
- tests/FSharpPlus.Tests/General.fs
https://github.com/dotnet/fsharp/pull/11603
> Support for %B

- src/FSharpPlus/Control/Tuple.fs
- src/FSharpPlus/Internals.fs
- src/FSharpPlus/Operators.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General.fs
This will enable:
- curryN
- uncurryN
for tuples of 2 to 7 elements.
More elements should in theory work but current Fable version is not able to compile the required trait calls.
> Fable compatibility for un/curry functions

- src/FSharpPlus/Operators.fs
Adding bindError, which I find myself reaching for when piping values, just for a more consistent style.
```
let subscribe profile watermark =
subscribeProfileAsResultT watermark profile
</ catch /> (UserProfiles.Subscribe.deactivateOrResubscribe mitimesUri profile)
|> ResultT.map ignore
```
Also, I've starting using fantomas to autoformat, which (currently) can't format `</ catch />` nicely. It becomes:
```
let subscribe profile watermark =
subscribeProfileAsResultT watermark profile
</ catch
/> (UserProfiles.Subscribe.deactivateOrResubscribe mitimesUri profile)
|> map ignore
```
I also had to recently train a new dev on code and catch and the </ and /> operators were kind of hard to explain.
Having `bindError` as an alternative style, looks like:
```
let subscribe profile watermark = …
```
> Add bindError -- flipped `catch` which is useful for piping

- src/FSharpPlus/Control/Monad.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Monad.fs
After testing CEs in Fable I just realized that the problem is the complex resolution of the `Delay` method.
This solution consists in leaving only the default Delay implementation available to Fable, which in theory is less efficient in some cases, but still better than nothing.
> Enable CEs in Fable

- src/FSharpPlus/Data/Cont.fs
- src/FSharpPlus/Data/Error.fs
- src/FSharpPlus/Data/Free.fs
- src/FSharpPlus/Data/Identity.fs
- src/FSharpPlus/Data/List.fs
- src/FSharpPlus/Data/Monoids.fs
- src/FSharpPlus/Data/NonEmptyList.fs
- src/FSharpPlus/Data/Option.fs
- src/FSharpPlus/Data/ParallelArray.fs
- src/FSharpPlus/Data/Reader.fs
- src/FSharpPlus/Data/Seq.fs
- src/FSharpPlus/Data/State.fs
- src/FSharpPlus/Data/Validation.fs
- src/FSharpPlus/Data/Writer.fs
- src/FSharpPlus/Data/ZipList.fs
- src/FSharpPlus/Extensions/Result.fs
This aims to add missing Lift 2/3 static members in order to be able to use up to `lift3` generic function without any type inference problems.
> + Missing Lift2 and Lift3

- Directory.Build.props
- src/FSharpPlus/Data/Cont.fs
- src/FSharpPlus/Data/Monoids.fs
- src/FSharpPlus/Data/Reader.fs
- src/FSharpPlus/Data/State.fs
- src/FSharpPlus/Data/Validation.fs
- src/FSharpPlus/Data/Writer.fs
- src/FSharpPlus/Operators.fs
Adding `<!>`, `*>` and `<*` as static members to:
- Const, Compose, Validation
- Reader, ReaderT
- State, StateT
- Writer, WriterT
- Cont, ContT
This will have the subtle advantage of having them available even if `FSharpPlus.Operators` is not in scope, which would in such case reduce compiler pressure.
> Add missing applicative operators to types

- docsrc/content/type-seqt.fsx
- src/FSharpPlus/Data/Seq.fs
- src/FSharpPlus/Extensions/AsyncEnumerable.fs
- src/FSharpPlus/Extensions/Observable.fs
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
- tests/FSharpPlus.Tests/SeqT.fs
The previous implementation was not adding any effect besides binding strategy.
With this implementation we can derive both `asyncSeq` as `type AsyncSeq<'T> = SeqT<Async<bool>, 'T>` and `taskSeq` as `type TaskSeq<'T> = SeqT<Task<bool>, 'T>` among combinations with other monads like `type AsyncResultSeq<'T, 'Error> = SeqT<ResultT<Async<Result<bool, 'Error>>, 'T>` .
This adds the interfaces `IEnumeratorM<'Monad<bool>, 'T>` and `IEnumerableM<'Monad<bool>, 'T>` which would ideally be an alias of `SeqT<'Monad<bool>, 'T>` but since as of F# 6 we can't create static members in interfaces we will have to rely in composition instead.
> Proper SeqT implementation

- docsrc/content/type-seqt.fsx
This is the direct translation of https://github.com/tpetricek/FSharp.AsyncExtensions/blob/master/samples/Crawler.fsx
> + Webcrawler sample from AsyncSeq post

- src/FSharpPlus/Control/Applicative.fs
> Make left zero dynamic (rewrite)

- src/FSharpPlus/Operators.fs
Apparently a bug in the compiler was fixed, let's see if it's true.
> Add explicit type parameters

- src/FSharpPlus/Builders.fs
> Use InlineIfLambda attribute in CEs

- src/FSharpPlus/Control/Applicative.fs
Reverts fsprojects/FSharpPlus#503 because of this:
```
> open FSharpPlus.Control ;;
> IsLeftZero.Invoke empty<OptionT<Task<Option<int>>>> ;;
Binding session to 'C:/Users/gmpl2/.nuget/packages/fsharpplus/1.3.0-ci02744/lib/net6.0/FSharpPlus.dll'...
System.TypeInitializationException: The type initializer for 'FSharpPlus.Control.IsLeftZeroHelper`1' threw an exception.
---> System.ArgumentException: The type or method has 2 generic parameter(s), but 1 generic argument(s) were provided. A generic argument must be provided for each generic parameter.
at System.RuntimeType.SanityCheckGenericArguments(RuntimeType[] genericArguments, RuntimeType[] genericParameters)
at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
at …
```
> Revert "Make left zero dynamic (rewrite)"

- src/FSharpPlus/Builders.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
Specialized builder for `Validation<_, _>` (this is without type parameters specified) has poor type inference.
A test is being added that shows the current limitation.
> Improve type inference for specialized applicative CE

- src/FSharpPlus/Extensions/ValueTask.fs
This PR does 2 things
- Add missing XML comments and apply formatting
- Avoid using `backgroundTask` CE, which has a bug that prevents F# 6 to compile it.
> Fix ValueTask

- docsrc/content/abstraction-alternative.fsx
- src/FSharpPlus/Control/Alternative.fs
The idea is that functions returning Alternatives are themselves Alternatives.
This will eventually allow using `choice` over a list of functions (ie: WebParts).
> + functions as Alternatives (conditionally)

- .github/workflows/fable.yml
Use fable with .net 7 installed.  
See https://github.com/fsprojects/FSharpPlus/pull/525 for why we did not upgrade to net7 for Fable CI
> net 7.0.200 for Fable

- src/FSharpPlus.Docs/Samples/Learn You a Haskell.fsx
There is a breaking change in the F# compiler which is now breaking our CI.
https://github.com/dotnet/fsharp/issues/15987
This will workaround that breaking change for the time being.
> Use strict monad in sample

- src/FSharpPlus/Control/Converter.fs
- tests/FSharpPlus.Tests/Parsing.fs
Functions `parse`  and `tryParse` should behave the same, the only difference should be in throwing or returning `None`.
> Adjust parse / tryParse

- src/FSharpPlus/Extensions/Task.fs
We normally uses `Task.FromValue` but nowadays, using the `task` CE the namespace `System.Threading.Tasks` is not always opened and opening it only to return a task doesn't feel so good.
Sometimes what I do is I use `result` but in some places is too generic.
Another option is writing `task { return x }` but I think is overkill.
Given that we have our Task module in scope with many functions, maybe natural way is to add one there like `List.singleton` does.
> Add a function for creating a Task from a value

- src/FSharpPlus/Extensions/Extensions.fs
> + Result.Sequence

- src/FSharpPlus/Extensions/Extensions.fs
- tests/benchmarks/Benchmarks.fsproj
- tests/benchmarks/ExtensionsBenchmarks.fs
- tests/benchmarks/Program.fs
- Add `Result.Sequence`
- Update `Option.Sequence`, `VOption.Sequence` to use `ArrayCollector`
> + Result.Sequence & Option|VOption use Accumulator

- src/FSharpPlus/Control/Traversable.fs
- src/FSharpPlus/Extensions/Extensions.fs
Use specific `Sequence` for equal `Traverse` instead of the generic one.
Fix issue in `ValueOption.Sequence` and `Option.Sequence`
> Use new [Option|ValueOption|Result|Choice].Sequence in Traverse

- src/FSharpPlus/Data/Validation.fs
For both `Option` and `ValueOption`
> + Validation.ofOptionWith

- src/FSharpPlus/Control/Collection.fs
- src/FSharpPlus/Extensions/List.fs
- tests/FSharpPlus.Tests/Collections.fs
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
- tests/FSharpPlus.Tests/General.fs
With the new `ListCollector` we can add an efficient implementation for lists.
> Add List.chunkBy

- docsrc/content/tutorial.fsx
This was issuing a warning about the indentation, which was workarounded with a #nowarn.
But now, in F# 8 / Net 8 the compilation breaks due to [strict indentation](https://devblogs.microsoft.com/dotnet/announcing-fsharp-8/#strict-indentation-rules) so now the fix is to add some indentation and hidden modules.
> Fix indentation in tutorial.fsx

- .config/dotnet-tools.json
- .github/workflows/dotnetcore.yml
- .github/workflows/fable.yml
- appveyor.yml
- global.json
> Net8 configuration

- src/FSharpPlus/Control/Applicative.fs
- src/FSharpPlus/Control/Functor.fs
- src/FSharpPlus/Internals.fs
- tests/FSharpPlus.Tests/General.fs
Same as #207 but rebased.
I gave it another try and looks like I found a way not to break anything, so no need to wait for v2.
This will allow Vector and Matrix to implement `IEnumerable`.
Another reason to implement this is removing dependencies between `NonEmptySeq<'T>` (now that F#8 allows static member on interfaces) and `FSharpPlus.Control` by creating its own static members #552 
Also to the original issues:
> Right now there are 2 issues ..
>  - Types implementing `IEnumerable<_>` would default to the `seq<_>` instance. This might be arguably desired.
>  - Types implementing `IEnumerable<_>` would default to the `seq<_>` instance, even if they implement their own applicative > instance. This is not acceptable.
.. I will amend the former like this:
- Types implementing …
> Remove subsumption from Applicatives

- src/FSharpPlus/Control/Applicative.fs
- src/FSharpPlus/Extensions/Dict.fs
- src/FSharpPlus/Extensions/IReadOnlyDictionary.fs
- tests/FSharpPlus.Tests/ComputationExpressions.fs
- tests/FSharpPlus.Tests/General.fs
Although dictionaries don't support the `Return` operation, we can go quite far with applicatives.
This is a good alternative to #448 instead of fighting the absence of `Return` we embrace it and add other missing methods in order to be able to use some applicative operations, including the applicative CE.
> Limited applicative support for dictionaries

- .config/dotnet-tools.json
- .github/workflows/fable.yml
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
- tests/FSharpPlus.Tests/General.fs
- tests/FSharpPlusFable.Tests/FSharpPlusFable.Tests.fsproj
- tests/FSharpPlusFable.Tests/FSharpTests/General.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Alternative.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Applicative.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Collections.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Foldable.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Indexable.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Monad.fs
- tests/FSharpPlusFable.Tests/fable3-global.json
- tests/FSharpPlusFable.Tests/global.json
- Add: .net8 target framework for F#+ library
- Update: F# language version to 8
- Fix: A unique overload for method 'DateTime' could not be determined
- Fix: Indentation warnings that has turned into compilation error
- Fix: Fable 3.7 runs with downgraded .net versions and target framework
> + .net8 target framework and F# language version 8

- src/FSharpPlus/Control/Monoid.fs
- src/FSharpPlus/Control/Numeric.fs
- src/FSharpPlus/Control/Tuple.fs
- src/FSharpPlus/Internals.fs
- src/FSharpPlus/Parsing.fs
Fable's helpers for tuple are no longer needed, Fable added direct support shortly after they were added.
There's also a Fable only warning about an upcast.
> Address some warnings

- docsrc/content/extensions.fsx
- src/FSharpPlus/Control/Indexable.fs
- src/FSharpPlus/Extensions/Array.fs
- src/FSharpPlus/Extensions/List.fs
- src/FSharpPlus/Extensions/ResizeArray.fs
- src/FSharpPlus/Extensions/Seq.fs
- src/FSharpPlus/Extensions/String.fs
- src/FSharpPlus/Internals.fs
- src/FSharpPlus/Operators.fs
- tests/FSharpPlus.Tests/General.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Indexable.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Util.fs
Closes #574
I was not able to build the test project, so I rely on CI to run them.
> Implement (try)FindLastSliceIndex

- src/FSharpPlus/Operators.fs
- tests/FSharpPlus.Tests/General.fs
This is related to #215 
After many years using F#+ with Functors, Applicatives and Monads found out that:
- Monadic code tends to read better in CEs
- Applicative code used to read good with applicative operators but since the addition of CEs for applicatives this is becoming the default to go
- Functors on the other side reads good with pipes, either by using `|> map` (or qualified map for better type inference) or by using `|>>`.
When it comes to composed effects we have Monad transformers which are not that great IMHO but it's the best we have so far to compose them, so we can keep writing then as CEs.
For applicatives the situation is much better as although they can be easily composed with `Compose` we can take advantage of `applicative2` and `applicative3` CEs.
Now the missing …
> Add "map squared" pipe operators

- src/FSharpPlus/Data/DList.fs
This code is a bit old and is claiming for some attention.
Also it's important to note there are some false statements in the comments: walking the DList is not O(n) but O(2n).
The advantage of DList is that it can add and also append lists in O(1), whereas append for other collections is slower.
> Updates to DList

- src/FSharpPlus/Extensions/Async.fs
- src/FSharpPlus/Extensions/AsyncEnumerable.fs
- src/FSharpPlus/Extensions/Extensions.fs
- src/FSharpPlus/FSharpPlus.fsproj
This is Eirik Tsarpalis `Async.AwaitTaskCorrect` [implementation](https://www.fssnip.net/7Rc/title/AsyncAwaitTaskCorrect).
It's likely to be [included in FSharp.Core](https://github.com/fsharp/fslang-suggestions/issues/840) in the near future, but we need it now
> Add (and use internally) Async.Await

- src/FSharpPlus/Control/Comonad.fs
- src/FSharpPlus/Control/Functor.fs
- src/FSharpPlus/Control/Monoid.fs
- src/FSharpPlus/Control/Traversable.fs
- src/FSharpPlus/Extensions/Async.fs
- src/FSharpPlus/Extensions/AsyncEnumerable.fs
- src/FSharpPlus/Extensions/Exception.fs
- src/FSharpPlus/Extensions/Extensions.fs
- src/FSharpPlus/Extensions/IReadOnlyCollection.fs
- src/FSharpPlus/Extensions/Task.fs
- src/FSharpPlus/Extensions/ValueTask.fs
- src/FSharpPlus/FSharpPlus.fsproj
- tests/FSharpPlus.Tests/Asyncs.fs
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
- tests/FSharpPlus.Tests/Task.fs
- tests/FSharpPlus.Tests/ValueTask.fs
We expect that `computation.zip` accumulates errors, for async, task and valueTask.
While trying to assert it, we realized we need to fix some stuff, including some FSharp.Core functions.
> Ensure proper 'zip-applicative' behavior for async computations

- src/FSharpPlus/Control/Applicative.fs
- src/FSharpPlus/Control/Comonad.fs
- src/FSharpPlus/Control/Monad.fs
- src/FSharpPlus/Control/ZipApplicative.fs
- src/FSharpPlus/Internals.fs
- tests/FSharpPlus.Tests/Asyncs.fs
- tests/FSharpPlus.Tests/Task.fs
- tests/FSharpPlus.Tests/ValueTask.fs
We need to make sure the non-seq traversals and in sync with the zip-applicative functions
> Assert proper non-seq traversals

- src/FSharpPlus/Control/Traversable.fs
- src/FSharpPlus/Extensions/Extensions.fs
This fixes #589 
The name chosen for the conflicting overload is `Async.SequentialLazy` as opposed to `Async.SequentialBlocking` as suggested in the original issue, although both describe what it does.
If you have a better name, please suggest.
> Rename Sequence overloads to Sequential

- src/FSharpPlus/Control/Traversable.fs
- tests/FSharpPlus.Tests/Asyncs.fs
- tests/FSharpPlus.Tests/Traversals.fs
- tests/FSharpPlusFable.Tests/FSharpTests/General/Traversable.fs
It seems non sequential traversals have better type inference that sequential ones.
So, the idea is to copy the relevant bits and see what happens.
It's interesting to note that the non-seq implementation has another additional benefit which is a micro optimization in that unless the collection is empty, it uses initially a `map` operation instead of a `return` / `pure` followed by `<*>` / `<.>`.
> Improve sequential traversals type inference

- .github/CODEOWNERS
Add additional default reviewers
Though it seems @pnobre is not part of FSprojects, so should be added to that.
> Add @pnobre

- src/FSharpPlus.TypeLevel/Data/Matrix.fs
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
- tests/FSharpPlus.Tests/Matrix.fs
- tests/FSharpPlus.Tests/TypeLevel.fs
This also makes `Vector<_, 'n>` and `Matrix<_, 'm, 'n>` monads.
ref: https://stackoverflow.com/questions/5802628/monad-instance-of-a-number-parameterised-vector
> Monad instance for `Vector` and `Matrix`

- src/FSharpPlus/Data/Seq.fs
- tests/FSharpPlus.Tests/SeqT.fs
These are functions that derive its implementation from `TryPIckM` and therefore don't return a sequence.
> Add pick related functions to SeqT

- .config/dotnet-tools.json
- src/FSharpPlus/Extensions/String.fs
Hi, I had an error with `String.endsWith` when compiling a project using FSharpPlus with Fable. `String.endsWith` was not surrounded by a `!FABLE_COMPILER` symbol condition.
A Fable maintainer [fixed my issue by making `String.endsWith` work with Fable, _as well as `String.startsWith`_](https://github.com/fable-compiler/Fable/issues/3934#issuecomment-2429149490).
This PR simply removes the `!FABLE_COMPILER` symbol condition around `String.startsWith` that is not needed anymore.
> Removed String.startsWith !FABLE_COMPILER condition

- src/FSharpPlus/Control/Traversable.fs
- src/FSharpPlus/Data/NonEmptyList.fs
- src/FSharpPlus/Extensions/Array.fs
- src/FSharpPlus/Extensions/List.fs
- src/FSharpPlus/Extensions/Seq.fs
- src/FSharpPlus/Lens.fs
This will add `cons` and `uncons` (and related) to places where it makes sense.
> Add cons and uncons to some collections

- src/FSharpPlus/Control/Monad.fs
- tests/FSharpPlus.Tests/FSharpPlus.Tests.fsproj
- tests/FSharpPlus.Tests/General.fs
- tests/FSharpPlus.Tests/Monads.fs
At the moment only `Map<_,_>` and `Dictionary<_,_>` have corresponding overloads.
> + Bind and Join for dict interfaces

- src/FSharpPlus/Control/Collection.fs
- src/FSharpPlus/Internals.fs
- tests/FSharpPlus.Tests/Collections.fs
> Fix internal Id type being selected in overload resolution

- src/FSharpPlus/Extensions/Extensions.fs
Bring missing functions from its `Result` counterpart.
> + Missing Sequential for Choice

- src/FSharpPlus/Control/Numeric.fs
- tests/FSharpPlus.Tests/Monoid.fs
The current Semigroup implementation for `Result` supports a neutral element `Error e` as long as `e` has a neutral element, effectively making it a Monoid.
Before this PR, the following line **doesn't compile**:
```fsharp
sum [Ok 1; Error (); Ok 3] ;;
-----------------^^
stdin(13,18): error FS0001: The type 'bigint' does not support a conversion to the type 'Result<int,unit>'
```
However, it **does compile and work as expected** when using the binary Semigroup operator (`++`), because the `zero` is never involved:
```fsharp
Ok 1 ++ Error () ++ Ok 3
// val it: Result<int,unit> = Ok 4
```
This PR makes the Monoid instance consistent by providing a `zero` operation for `Result`, allowing `sum` and similar generic functions to work correctly. A similar addition for `Choice<'t1, 't2>` will be …
> + Zero for Result and Choice

- src/FSharpPlus/Control/Applicative.fs
- src/FSharpPlus/Control/Foldable.fs
- src/FSharpPlus/Control/Functor.fs
- src/FSharpPlus/Control/Monad.fs
- src/FSharpPlus/Extensions/Dict.fs
- src/FSharpPlus/Extensions/Dictionary.fs
- src/FSharpPlus/Extensions/IReadOnlyDictionary.fs
- src/FSharpPlus/Extensions/Map.fs
- tests/FSharpPlus.Tests/Folds.fs
There were several missing utility functions for dictionary-like data structures. This PR includes:
- Additional helper functions for types that implement dictionary-like interfaces (IDictionary, Map, etc.)
- Enhanced support for common dictionary operations that were previously missing from the library
- Improved consistency in the API surface area for dict-like types
- Internal re-use of such helper functions, improving readability of existing code
This PR fills gaps in the dictionary/map function coverage, making the library more complete and consistent for developers working with key-value data structures.
> + Missing dictionary utility functions
